import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sgaju_000' at '10/25/16 12:50 PM' with Gradle 2.14.1
 *
 * @author sgaju_000, @date 10/25/16 12:50 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       
    }
}
